### ISSUE TITLE
Πληροφορίες για το τρέξιμο του προγράμματος.

### ISSUE THREAD

**Issue by harmine21** [panagiotisgia/arbitage_betting#1]
Μπορείτε να προσθέσετε επιπλέον πληροφορίες σχετικά με το πώς τρέχει το πρόγραμμα;

Έκανα install τα requirements και μετά έτρεξα το main.ipynb από το Jupyter Notebook και μου έβγαλε error ότι δεν βρίσκει πού είναι τα functions για το scraping. Τα έβαλα στο ίδιο directory με το script και τα πήρε, αλλά δημιουργούνται κιάλλα errors.

Ευχαριστώ.

**Comment by panagiotisgia** [comment]
Καλησπέρα, 

Έχω κάνει κάποιες αλλαγές και έχω προσθέσει νέες εκδόσεις στις βιβλιοθήκες. 

Το κυριώς πρόγραμμα είναι το main.ipynb 

Έχω προσθέσει αρχικά το 

import sys
sys.path.append('..')  # Adding the parent directory to the path

ετσι ώστε να βρει τα functions και να τα τρέξει. 
Προσοχή εδώ γιατί ανοίγει browser σε headless mode.

Επειδή είναι ένα project που δεν το συντηρώ και καθώς τα site των στοιχηματικών είναι δυναμικά και αλλάζουν συχνά, μπορείς να μεταβεις στο web_scrape_functions_deb και να τρέξεις τα αρχεία novibet.ipynb και stoiximan.ipynb βήμα βήμα και να δεις που σκάει η διαδικασία γιατί μπορεί κάτι να έχει αλλάξει στο site.
Σου ανοίγει κανονικά chrome browser και βλέπεις τι γίνεται. 

Έχοντας κάνει το debugging αν θες να το αυτοματοποιήσεις μπορείς να βάλεις τις αλλαγές σου μέσα στα web_scrape_funtions στα αντίστοιχα modules και μετά να τρέξεις το main.ipynb 

Αν έχεις όποια άλλη απορία σχετικά με την διαδικασία μπορείς να μου στείλεις
